<?php

/**
 * Implements hook_theme().
 */
function nodecontent_theme($existing, $type, $theme, $path) {
  return array(
    'relatedlinks' => array(
      'template' => 'templates/relatedlinks',
      'variables' => array('viewresult' => NULL, 'tags' => NULL),
    ),
  );
}

/**
 * Implements hook_node_view().
 */
  function nodecontent_node_view($node, $view_mode, $langcode) {
    if ($view_mode == 'full') {
      $node->content['relatedlinks'] = nodecontent_get_related_links($node->field_tags,$node->language);
    }
  }

function nodecontent_get_related_links($tags,$language) {

  $argument = '';
  foreach ($tags[$language] as $key => $value) {
    $argument .= $value['tid'] . '+'; // Adding the ids as string with '+'
  }

  $argument = substr($argument, 0,-1); // Removing the last '+' sign.

  $output = array(
    '#theme' => 'relatedlinks',
    '#viewresult' => views_embed_view('related_links','block',$argument),
    '#tags' => $tags,
  );

  return $output;
}